name: Briefing Diário

on:
  schedule:
    - cron: '0 10 * * *' # Roda todo dia às 07:00 Brasil (10:00 UTC)
  workflow_dispatch: # Permite rodar manualmente clicando no botão

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' # <--- ATUALIZADO PARA 3.11 (A CORREÇÃO MÁGICA)

    - name: Instalar dependências
      run: |
        pip install -r requirements.txt

    - name: Rodar Robô
      env:
        GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        GCP_JSON: ${{ secrets.GCP_JSON }}
      run: python main.py
